### PR TITLE
Added a example of toxicity classification using python and Tkinter library for GUI and also added a example demonstrating how to use weaviate in NodeJs and express server 

### PR DESCRIPTION
**Pull request by YASH-GU24**

### CODE REVIEW

**Comment by YASH-GU24** [comment]
I agree with CLA.

**Comment by YASH-GU24** [comment]
> Hi @YASH-GU24
> 
> First of all, thanks for your contribution!
> 
> I've seen the code and readme, and I've one request before I will merge your PR. In your readme, you mention 'Make Sure docker file is running.'. However, I can't find a docker file in your folder. Can you add that please? In this dockerfile there is essential information which one needs to be able to run your example, such as which modules it uses.

Thanks for pointing that out!, Now I have added dockerfile for both examples.

**Comment by bobvanluijt** [comment]
Hola @laura-ham - I notice that this one is already merged but you might want to reverse and remove the node_modules folder 👍

**Comment by raam86** [comment]
Usually node modules are not not committed to git, I suggest removing them.

**Pull request merged**
