### PR TITLE
Add NodeJS data loader to JS Movies example

### PR DESCRIPTION
**Pull request by lmangani**
The NodeJS examples requires python to load the data (although the package.json suggests a js script already existed?)
This simple loader should produce the same outcome as the python one for pure NodeJS execution of the example.

**Testing needed!**

### CODE REVIEW

**Comment by lmangani** [comment]
boop beep agree with the CLA

**Comment by bobvanluijt** [comment]
Thanks for the contribution @lmangani! 

Hi @sebawita – can you review, please?

**Review by sebawita — APPROVED** [review]
Thank you for your submission.
The changes you proposed look good to me.
I've made a few modifications and I think we are good to go.

**Comment by lmangani** [comment]
Thanks for accepting the contributions and for the great project!

**Pull request merged**
